[package]
name = "atoma-tdx"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
atoma-sui = { workspace = true }
dcap-rs = { workspace = true }
fastcrypto = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
tdx = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
