{{- if .Values.atomaNode.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.atomaNode.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.atomaNode.ingress.className }}
  tls:
    - hosts:
        {{- range .Values.atomaNode.ingress.hosts }}
        - {{ .host }}
        {{- end }}
      secretName: {{ .Release.Name }}-tls
  rules:
    {{- range .Values.atomaNode.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-atoma-node
                port:
                  number: {{ $.Values.atomaNode.service.port }}
          {{- if $.Values.vllm.enabled }}
          - path: /vllm
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-vllm-0
                port:
                  number: {{ $.Values.vllm.service.port }}
          {{- end }}
          {{- if $.Values.sglang.enabled }}
          - path: /sglang
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-sglang
                port:
                  number: {{ $.Values.sglang.service.port }}
          {{- end }}
    {{- end }}
{{- end }}