{{- if .Values.vllm.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vllm
  labels:
    app: vllm
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.vllm.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: vllm
    release: {{ .Release.Name }}
---
{{- end }}
{{- if .Values.sglang.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sglang
  labels:
    app: sglang
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.sglang.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.sglang.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: sglang
    release: {{ .Release.Name }}
{{- end }}
