version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

  # Optionally keep Actions up to date too
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
