[workspace]
resolver = "2"

members = [ 
    "atoma-service",
    "atoma-state",
    "atoma-sui",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.81"
async-trait = "0.1.78"
atoma-state = { path = "./atoma-state" }
atoma-sui = { path = "./atoma-sui" }
axum = "0.7.5"
base64 = "0.22.1"
blake2 = "0.10.6"
candle = { git = "https://github.com/huggingface/candle", package = "candle-core", branch = "main" }
candle-flash-attn = { git = "https://github.com/huggingface/candle", package = "candle-flash-attn", branch = "main" }
candle-nn = { git = "https://github.com/huggingface/candle", package = "candle-nn", branch = "main" }
candle-transformers = { git = "https://github.com/huggingface/candle", package = "candle-transformers", branch = "main" }
clap = "4.5.4"
config = "0.14.0"
cudarc = { version = "0.12.0", features = [
    "std",
    "cublas",
    "cublaslt",
    "curand",
    "driver",
    "nvrtc",
    "f16",
    "cuda-version-from-build-system",
    "dynamic-linking",
], default-features = false }
cuda-runtime-sys = "0.3.0-alpha.1"
dotenv = "0.15.0"
ed25519-dalek = "2"
ethers = "2.0.14"
futures = "0.3.30"
futures-util = "0.3.30"
http = "0.2"
gql_client = "1.0.7"
half = { version = "2.3.1", features = [
    "num-traits",
    "use-intrinsics",
    "rand_distr",
] }
hex = "0.4.3"
hf-hub = "0.3.2"
image = { version = "0.25.2", default-features = false, features = [
    "jpeg",
    "png",
] }
indexmap = "2.2.6"
ipfs-api-backend-hyper = "0.6.0"
metrics = "0.23"
metrics-exporter-prometheus = "0.14.0"
p256 = "0.13.2"
rand = "0.8.5"
rayon = "1.10.0"
reqwest = "0.12.1"
rmp-serde = "1.3.0"
rs_merkle = "1.4.2"
secp256k1 = "0.30.0"
serde = "1.0.204"
serde_json = "1.0.120"
sha2 = "0.10.8"
sqlx = "0.8.2"
sui-keys = { git = "https://github.com/mystenlabs/sui", package = "sui-keys" }
sui-sdk = { git = "https://github.com/mystenlabs/sui", package = "sui-sdk" }
thiserror = "1.0.58"
tokenizers = "0.15.2"
tokio = "1.36.0"
toml = "0.8.12"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
url = "2.5.2"
utoipa = "5.1.1"
utoipa-swagger-ui = "8.0.1"
