[workspace]
resolver = "2"

members = ["atoma-event-subscribe", "atoma-inference", "atoma-networking", "atoma-json-rpc", "atoma-storage"]

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
async-trait = "0.1.78"
candle = { git = "https://github.com/huggingface/candle", package = "candle-core", version = "0.4.2" }
candle-transformers = { git = "https://github.com/huggingface/candle", package = "candle-transformers", version = "0.4.2" }
ed25519-consensus = "2.1.0"
serde = "1.0.197"
thiserror = "1.0.58"
tokenizers = "0.15.2"
tokio = "1.36.0"
tracing = "0.1.40"
