[workspace]
resolver = "2"
edition = "2021"

members = [
  "atoma-event-subscribe",
  "atoma-inference",
  "atoma-networking",
  "atoma-json-rpc",
  "atoma-storage",
]

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
reqwest = "0.12.1"
anyhow = "1.0.81"
async-trait = "0.1.78"
candle = { git = "https://github.com/huggingface/candle", package = "candle-core", version = "0.4.2" }
candle-flash-attn = { git = "https://github.com/huggingface/candle", package = "candle-flash-attn", version = "0.4.2" }
candle-nn = { git = "https://github.com/huggingface/candle", package = "candle-nn", version = "0.4.2" }
candle-transformers = { git = "https://github.com/huggingface/candle", package = "candle-transformers", version = "0.4.2" }
config = "0.14.0"
dotenv = "0.15.0"
ed25519-consensus = "2.1.0"
futures = "0.3.30"
hf-hub = "0.3.2"
clap = "4.5.3"
image = { version = "0.25.0", default-features = false, features = [
  "jpeg",
  "png",
] }
serde = "1.0.197"
serde_json = "1.0.114"
rand = "0.8.5"
thiserror = "1.0.58"
tokenizers = "0.15.2"
tokio = "1.36.0"
toml = "0.8.12"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
