services:
  vllm:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ${HF_CACHE_PATH:-~/.cache/huggingface}:/root/.cache/huggingface
    env_file:
      - .env
    ports:
      - "${INFERENCE_SERVER_PORT:-8000}:8000"
    ipc: host
    command: --model ${MODEL} --max-model-len ${MAX_MODEL_LEN} --tensor-parallel-size ${TENSOR_PARALLEL_SIZE}
    networks:
      - atoma-network

  atoma-node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.toml:/app/config.toml
      - ./logs:/app/logs
      - ${SUI_CONFIG_PATH:-~/.sui/sui_config}:/root/.sui/sui_config
      - ./data:/app/data
    env_file:
      - .env
    ports:
      - "${ATOMA_SERVICE_PORT:-3000}:3000"  # Expose Atoma service port
    depends_on:
      - vllm
    networks:
      - atoma-network

networks:
  atoma-network:
    driver: bridge
