services:
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=atoma
      - POSTGRES_USER=atoma
      - POSTGRES_PASSWORD=atoma
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
