# Base configuration for Atoma services
x-atoma-service: &atoma-service
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ./config.toml:/app/config.toml
    - ./logs:/app/logs
    - ${SUI_CONFIG_PATH:-~/.sui/sui_config}:/root/.sui/sui_config
    - ./data:/app/data
  env_file: .env
  networks:
    - atoma-network

# Base configuration for inference services
x-inference-service: &inference-service
  runtime: nvidia
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
  volumes:
    - ${HF_CACHE_PATH:-~/.cache/huggingface}:/root/.cache/huggingface
  env_file: .env
  networks:
    - atoma-network

services:
  # Updated atoma-node service
  atoma-node:
    <<: *atoma-service
    build:
      args:
        BINARY: atoma-node
    ports:
      - "${ATOMA_SERVICE_PORT:-3000}:3000"
      - "${ATOMA_DAEMON_PORT:-3001}:3001"
    depends_on:
      vllm:
        condition: service_started
    command: sh -c "./atoma-node & ./atoma-daemon"

  # Updated inference services using base configuration
  vllm:
    <<: *inference-service
    container_name: chat-completions
    profiles: [chat_completions_vllm]
    image: vllm/vllm-openai:v0.6.3
    ports:
      - "${CHAT_COMPLETIONS_SERVER_PORT}:8000"
    ipc: host
    command: --model ${CHAT_COMPLETIONS_MODEL} --max-model-len ${CHAT_COMPLETIONS_MAX_MODEL_LEN} --tensor-parallel-size ${VLLM_TENSOR_PARALLEL_SIZE}

  tei:
    <<: *inference-service
    container_name: embeddings
    profiles: [embeddings_tei]
    image: ${TEI_IMAGE}
    ports:
      - "${EMBEDDINGS_SERVER_PORT}:80"
    command: --model-id ${EMBEDDINGS_MODEL} --huggingface-hub-cache /root/.cache/huggingface/hub

  mistralrs:
    <<: *inference-service
    container_name: image-generations
    profiles: [image_generations_mistralrs]
    image: ${MISTRALRS_IMAGE}
    ports:
      - "${IMAGE_GENERATIONS_SERVER_PORT}:80"
    command: diffusion-plain -m ${IMAGE_GENERATIONS_MODEL}

networks:
  atoma-network:
    driver: bridge
