services:
  atoma-node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.toml:/app/config.toml
      - ./logs:/app/logs
      - ${SUI_CONFIG_PATH:-~/.sui/sui_config}:/root/.sui/sui_config
      - ./data:/app/data
    env_file: .env
    ports:
      - "${ATOMA_SERVICE_PORT:-3000}:3000"  # Expose Atoma service port
    depends_on:
      - vllm
    networks: atoma-network

  vllm:
    container_name: chat-completions
    profiles: [chat_completions_vllm]
    image: vllm/vllm-openai:v0.6.3
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ${HF_CACHE_PATH:-~/.cache/huggingface}:/root/.cache/huggingface
    env_file: .env
    ports:
      - "${CHAT_COMPLETIONS_SERVER_PORT}:8000"
    ipc: host
    command: --model ${CHAT_COMPLETIONS_MODEL} --max-model-len ${CHAT_COMPLETIONS_MAX_MODEL_LEN} --tensor-parallel-size ${VLLM_TENSOR_PARALLEL_SIZE}
    networks: atoma-network

  atoma-node:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TRACE_LEVEL: ${TRACE_LEVEL:-info}
    volumes:
      - ${HF_CACHE_PATH:-~/.cache/huggingface}:/root/.cache/huggingface
    env_file: .env
    ports:
      - "${ATOMA_SERVICE_PORT:-3000}:3000"  # Expose Atoma service port
      - "${ATOMA_DAEMON_PORT:-3001}:3001"  # Expose Atoma daemon port
    depends_on:
      - vllm
    networks:
      - atoma-network

networks:
  atoma-network:
    driver: bridge
