services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: atoma
      POSTGRES_USER: atoma
      POSTGRES_PASSWORD: atoma
    ports:
      - 5432:5432

volumes:
  postgres-data:
