global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "atoma-node"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["atoma-node:3000"]

  - job_name: "atoma-node-sglang"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["atoma-node-sglang:50000"]

  - job_name: "vllm1"
    metrics_path: "/metrics"
    scrape_interval: 500ms
    static_configs:
      - targets: ["vllm1:8000"]

  - job_name: "vllm2"
    metrics_path: "/metrics"
    scrape_interval: 500ms
    static_configs:
      - targets: ["vllm2:8000"]

  - job_name: "vllm3"
    metrics_path: "/metrics"
    scrape_interval: 500ms
    static_configs:
      - targets: ["vllm3:8000"]

  - job_name: "vllm4"
    metrics_path: "/metrics"
    scrape_interval: 500ms
    static_configs:
      - targets: ["vllm4:8000"]

  - job_name: "vllm5"
    metrics_path: "/metrics"
    scrape_interval: 500ms
    static_configs:
      - targets: ["vllm5:8000"]

  - job_name: "vllm6"
    metrics_path: "/metrics"
    scrape_interval: 500ms
    static_configs:
      - targets: ["vllm6:8000"]

  - job_name: "vllm7"
    metrics_path: "/metrics"
    scrape_interval: 500ms
    static_configs:
      - targets: ["vllm7:8000"]

  - job_name: "vllm8"
    metrics_path: "/metrics"
    scrape_interval: 500ms
    static_configs:
      - targets: ["vllm8:8000"]

  - job_name: "otel-collector"
    scrape_interval: 10s
    static_configs:
      - targets: ["otel-collector:8889"]
    metric_relabel_configs:
      - action: labelmap
        regex: ^(atoma|libp2p)_(.+)$
        replacement: $1_$2

  - job_name: "sglang"
    metrics_path: "/metrics"
    scrape_interval: 250ms
    static_configs:
      - targets: ["host.docker.internal:3000"]

  - job_name: "node-exporter"
    scrape_interval: 10s
    static_configs:
      - targets: ["node-exporter:9100"]
