global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "atoma-node-confidential"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["atoma-node-confidential:3000"]

  - job_name: "atoma-node-non-confidential"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["atoma-node-non-confidential:3000"]

  - job_name: "vllm"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["vllm:8000"]

  - job_name: "otel-collector"
    scrape_interval: 10s
    static_configs:
      - targets: ["otel-collector:8889"]
    metric_relabel_configs:
      - action: labelmap
        regex: ^(atoma|libp2p)_(.+)$
        replacement: $1_$2
