global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "atoma-node-confidential"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["atoma-node-confidential:3000"]

  - job_name: "atoma-node-non-confidential"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["atoma-node-non-confidential:3000"]

  - job_name: "vllm1"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["vllm1:8000"]

  - job_name: "vllm2"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["vllm2:8000"]

  - job_name: "vllm3"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["vllm3:8000"]

  - job_name: "vllm4"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["vllm4:8000"]

  - job_name: "vllm5"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["vllm5:8000"]

  - job_name: "vllm6"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["vllm6:8000"]

  - job_name: "vllm7"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["vllm7:8000"]

  - job_name: "vllm8"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["vllm8:8000"]

  - job_name: "otel-collector"
    scrape_interval: 10s
    static_configs:
      - targets: ["otel-collector:8889"]
    metric_relabel_configs:
      - action: labelmap
        regex: ^(atoma|libp2p)_(.+)$
        replacement: $1_$2
  - job_name: "postgres_archival"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["postgres-db:5432"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: "(.*):.*"
        replacement: "$1"
