[package]
name = "atoma-p2p"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
blake3 = { workspace = true }
ciborium = { workspace = true }
chrono = { workspace = true }
config = { workspace = true }
libp2p = { workspace = true, features = [ "tokio", "identify", "gossipsub", "mdns", "kad", "noise", "macros", "tcp", "yamux", "quic"] }
fastcrypto = { workspace = true }
flume = { workspace = true }
futures = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sui-keys = { workspace = true }
sui-sdk = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
tempfile = { workspace = true }
