[package]
name = "atoma-p2p"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
blake3 = { workspace = true }
ciborium = { workspace = true }
chrono = { workspace = true }
config = { workspace = true }
isocountry = { workspace = true }
libp2p = { workspace = true, features = [
	"tokio",
	"dns",
	"identify",
	"gossipsub",
	"mdns",
	"kad",
	"macros",
	"quic",
	"tcp",
	"yamux",
	"noise",
	"metrics",
] }
fastcrypto = { workspace = true }
flume = { workspace = true }
futures = { workspace = true }
nvml-wrapper = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sui-keys = { workspace = true }
sui-sdk = { workspace = true }
sysinfo = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
url = { workspace = true }
validator = { workspace = true, features = ["derive"] }
opentelemetry = { workspace = true }
once_cell = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
tempfile = { workspace = true }
