[package]
name = "atoma-crypto"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2.workspace = true

[dev-dependencies]
rand.workspace = true
