[package]
name = "atoma-waku"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
rand.workspace = true
tracing.workspace = true
chrono.workspace = true
prost.workspace = true
waku-bindings.workspace = true
