[package]
name = "atoma-daemon"
version.workspace = true
edition.workspace = true

[dependencies]
axum = { workspace = true }
atoma-state = { workspace = true }
atoma-sui = { workspace = true }
sui-sdk = { workspace = true }
tracing = { workspace = true }
