[package]
name = "atoma-sui"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sui-sdk.workspace = true
thiserror.workspace = true
