[package]
name = "solana"
edition = "2021"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util.workspace = true
# solana-client.workspace = true
# solana-sdk.workspace = true
tokio.workspace = true
