pub(crate) const PROMPTS: &[&str] = &[
    "The sun set behind the mountains, painting the sky in shades of orange and purple.",
    "She walked through the forest, listening to the rustling of leaves under her feet.",
    "The old man sat on the park bench, feeding breadcrumbs to the pigeons.",
    "As the train pulled into the station, he felt a sense of excitement for the journey ahead.",
    "The city streets were bustling with activity, as people hurried to their destinations.",
    "She looked out the window and watched the raindrops fall gently onto the pavement.",
    "In the quiet of the night, he could hear the distant sound of crickets chirping.",
    "The smell of freshly baked bread filled the air as she entered the bakery.",
    "He sat by the fireplace, lost in thought as the flames danced before him.",
    "The waves crashed against the shore, their rhythmic sound soothing her troubled mind.",
    "She gazed up at the stars, feeling small yet connected to the universe.",
    "The smell of coffee wafted through the air, inviting her to take a sip.",
    "He laughed as he chased after the playful puppy, enjoying the simple pleasure of companionship.",
    "She closed her eyes and let the music wash over her, transporting her to another world.",
    "The smell of flowers filled the garden, attracting bees and butterflies alike.",
    "He took a deep breath and plunged into the icy waters, feeling alive and invigorated.",
    "As she reached the mountaintop, she was greeted by a breathtaking view of the valley below.",
    "The sound of children's laughter echoed through the playground, bringing a smile to her face.",
    "He savored the taste of the freshly picked strawberries, their sweetness exploding on his tongue.",
    "She felt a sense of peace wash over her as she practiced yoga in the park.",
    "The sound of church bells ringing in the distance signaled the start of a new day.",
    "He watched in awe as the fireworks lit up the night sky, painting it in vibrant colors.",
    "She felt a sense of accomplishment as she crossed the finish line, completing her first marathon.",
    "The smell of rain on hot pavement filled the air, bringing relief from the summer heat.",
    "He marveled at the intricate patterns of the snowflakes as they fell softly to the ground.",
    "She sat on the swing, feeling the wind in her hair and the sun on her face.",
    "The sound of thunder rumbled in the distance, signaling an approaching storm.",
    "He listened to the sound of waves crashing against the rocks, feeling at peace with the world.",
    "She watched as the leaves changed colors, ushering in the beauty of autumn.",
    "The smell of barbecue filled the air as he fired up the grill for a summer cookout.",
    "He felt a sense of nostalgia as he flipped through old photographs, reliving cherished memories.",
    "She closed her eyes and listened to the sound of her own heartbeat, feeling alive and present in the moment.",
    "The taste of hot chocolate warmed her from the inside out on a cold winter's day.",
    "He watched as the clouds drifted lazily across the sky, their shapes morphing into fantastical creatures.",
    "She felt a sense of wonder as she explored the hidden nooks and crannies of an old bookstore.",
    "The smell of freshly cut grass reminded him of carefree childhood days spent playing in the park.",
    "He sat by the window and watched the world go by, lost in his own thoughts.",
    "She felt a surge of adrenaline as she jumped out of the plane, skydiving for the first time.",
    "The sound of birds chirping in the morning signaled the start of a new day.",
    "He watched in awe as the full moon cast its silver glow over the landscape.",
    "She felt a sense of pride as she watched her garden flourish, blooming with colorful flowers.",
    "The taste of ripe watermelon brought back memories of lazy summer afternoons spent with friends.",
    "He listened to the sound of his own footsteps echoing through the empty streets, feeling a sense of solitude.",
    "She felt a sense of belonging as she sat around the campfire, sharing stories with friends.",
    "The smell of cinnamon and spices filled the kitchen as she baked a batch of cookies.",
    "He felt a sense of accomplishment as he reached the summit of the mountain, conquering his fears.",
    "She watched as the first snowflakes of winter fell gently to the ground, blanketing the world in white.",
    "The sound of a crackling fire filled the cabin, warming her on a chilly winter's night.",
    "He felt a sense of awe as he looked up at the towering skyscrapers, marveling at human ingenuity.",
    "She closed her eyes and listened to the sound of the waves crashing against the shore, feeling at peace.",
    "The taste of freshly squeezed lemonade cooled her down on a hot summer day.",
    "He watched as the leaves danced in the wind, their colors swirling in a mesmerizing display.",
    "She felt a sense of freedom as she rode her bike through the countryside, the wind in her hair.",
    "The smell of pine trees filled the air as he hiked through the forest, reconnecting with nature."
];
