[package]
name = "atoma-utils"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
fastcrypto.workspace = true
sui-sdk = { workspace = true }
tokio.workspace = true
tracing.workspace = true
