name: Coverage

on:
  pull_request:

env:
  toolchain: stable
  CARGO_HTTP_MULTIPLEXING: false
  CARGO_TERM_COLOR: always
  CARGO_UNSTABLE_SPARSE_REGISTRY: true
  CARGO_INCREMENTAL: 0
  TERM: unknown

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: atoma
          POSTGRES_USER: atoma
          POSTGRES_PASSWORD: atoma
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libtss2-dev
        timeout-minutes: 5

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-directories: |
            ~/.cargo/registry
            ~/.cargo/git
            target

      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov
        timeout-minutes: 5

      - name: Generate coverage
        run: |
          RUSTFLAGS="-C target-cpu=native -C opt-level=2" cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info --jobs 2
        timeout-minutes: 30

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
        timeout-minutes: 5
