[package]
name = "inference"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait.workspace = true
ed25519-consensus.workspace = true
tch.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full", "tracing"] }
tracing.workspace = true
