[package]
name = "inference"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait.workspace = true
candle.workspace = true
candle-transformers.workspace = true
ed25519-consensus.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
tokenizers.workspace = true
tokio = { workspace = true, features = ["full", "tracing"] }
tracing.workspace = true
